from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from rac.src.local_evidence_resolver import resolve_state_evidence
from rac.src.mock_pipeline import build_factor_weighting_explanation, run_mock_pipeline, slugify


def markdown_escape(value: object) -> str:
    text = str(value)
    text = text.replace("|", "\\|")
    text = text.replace("\n", "<br>")
    return text


def compact_snippet(text: str, *, max_chars: int = 320) -> str:
    text = re.sub(r"\s+", " ", text).strip()

    if len(text) <= max_chars:
        return text

    return text[: max_chars - 3].rstrip() + "..."


def build_grounded_evidence_rows(resolver_result: dict[str, Any]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []

    for packet in resolver_result["resolved_packets"]:
        snippets = packet.get("snippets", [])

        if not snippets:
            rows.append({
                "factor_id": packet["factor_id"],
                "evidence_id": packet["evidence_id"],
                "source_path": packet["source_path"],
                "grounding_role": packet.get("grounding_role", "unknown"),
                "grounding_status": packet["grounding_status"],
                "line_range": "n/a",
                "matched_terms": [],
                "snippet": ""
            })
            continue

        first = snippets[0]
        line_start = first.get("line_start")
        line_end = first.get("line_end")
        line_range = f"{line_start}-{line_end}" if line_start and line_end else "n/a"

        rows.append({
            "factor_id": packet["factor_id"],
            "evidence_id": packet["evidence_id"],
            "source_path": packet["source_path"],
            "grounding_role": packet.get("grounding_role", "unknown"),
            "grounding_status": packet["grounding_status"],
            "line_range": line_range,
            "matched_terms": first.get("matched_terms", []),
            "snippet": compact_snippet(first.get("text", ""))
        })

    return rows





def calculate_evidence_coverage_score(state: dict[str, Any]) -> dict[str, Any]:
    grounded = state.get("grounded_evidence", {})
    summary = grounded.get("summary", {}) if isinstance(grounded, dict) else {}

    total_packets = int(summary.get("total_packets", 0))
    keyword_matched_packets = int(summary.get("keyword_matched_count", 0))
    boundary_matched_packets = int(summary.get("boundary_matched_count", 0))
    fallback_packets = int(summary.get("fallback_count", 0))
    missing_source_files = int(summary.get("source_missing_count", 0))

    if total_packets == 0:
        direct_evidence_rate = 0.0
        supported_or_boundary_rate = 0.0
    else:
        direct_evidence_rate = keyword_matched_packets / total_packets
        supported_or_boundary_rate = (keyword_matched_packets + boundary_matched_packets) / total_packets

    no_missing_source_file_score = 1.0 if missing_source_files == 0 else 0.0
    no_fallback_score = 1.0 if fallback_packets == 0 else 0.0

    score = (
        0.45 * direct_evidence_rate
        + 0.25 * supported_or_boundary_rate
        + 0.15 * no_missing_source_file_score
        + 0.15 * no_fallback_score
    )

    score = max(0.0, min(1.0, score))

    return {
        "score": score,
        "total_packets": total_packets,
        "keyword_matched_packets": keyword_matched_packets,
        "boundary_matched_packets": boundary_matched_packets,
        "fallback_packets": fallback_packets,
        "missing_source_files": missing_source_files,
        "direct_evidence_rate": direct_evidence_rate,
        "supported_or_boundary_rate": supported_or_boundary_rate,
        "no_missing_source_file_score": no_missing_source_file_score,
        "no_fallback_score": no_fallback_score,
    }


def write_grounded_final_report(state: dict[str, Any]) -> str:
    grounded = state["grounded_evidence"]
    summary = grounded["summary"]
    rows = build_grounded_evidence_rows(grounded)

    factor_by_id = {factor["factor_id"]: factor for factor in state["factors"]}

    lines: list[str] = []

    lines.append("# Grounded RAC Report")
    lines.append("")
    lines.append("## 1. Direct Answer")
    lines.append("")
    lines.append(state["belief_update"]["claim"])
    lines.append("")
    lines.append(
        "This report is generated by the deterministic RAC pipeline with local evidence grounding. "
        "It does not call an LLM, vector database, or live backend service."
    )
    lines.append("")

    lines.append("## 2. Question Type")
    lines.append("")
    lines.append(f"- Question type: {state['question_type']}")
    lines.append(f"- Domain: {state['domain']}")
    lines.append("")

    lines.append("## 3. Factor Weights")
    lines.append("")
    weighting_explanation = build_factor_weighting_explanation(
        state["question_type"],
        state["factor_weights"],
    )
    lines.append("### 3a. How Factor Weights Are Generated")
    lines.append("")
    lines.append(
        "Factor weights are generated by deterministic heuristic bucket assignment "
        "inside `rac/src/mock_pipeline.py`: not by a learned model, "
        "not by direct calculation from observed metric tables, "
        "not as probabilities, and not as optimized business thresholds."
    )
    lines.append("")
    lines.append("| Bucket | Weight | Rule | Factors in This Report |")
    lines.append("|---|---:|---|---|")
    for bucket in ["high", "medium", "default"]:
        members = weighting_explanation["bucket_members"].get(bucket, [])
        lines.append(
            "| "
            + markdown_escape(bucket)
            + " | "
            + f"{weighting_explanation['bucket_values'][bucket]:.2f}"
            + " | "
            + markdown_escape(weighting_explanation["bucket_reasons"][bucket])
            + " | "
            + markdown_escape(", ".join(members) if members else "none")
            + " |"
        )
    lines.append("")
    lines.append("Weighting limitations:")
    lines.append("")
    for limitation in weighting_explanation["limitations"]:
        lines.append(f"- {limitation}")
    lines.append("")
    lines.append("### 3b. Factor Weights Used in This Report")
    lines.append("")
    lines.append("| Factor | Weight | Bucket | Evidence Status | Why It Matters |")
    lines.append("|---|---:|---|---|---|")

    for item in state["factor_weights"]:
        factor = factor_by_id[item["factor_id"]]
        lines.append(
            "| "
            + markdown_escape(factor["factor_id"])
            + " | "
            + f"{item['weight']:.2f}"
            + " | "
            + markdown_escape(item.get("weight_bucket", "unknown"))
            + " | "
            + markdown_escape(item["evidence_status"])
            + " | "
            + markdown_escape(item["weight_reason"])
            + " |"
        )

    lines.append("")
    lines.append("## 4. Local Evidence Grounding")
    lines.append("")
    lines.append(f"- Total evidence packets: {summary['total_packets']}")
    lines.append(f"- Keyword matched packets: {summary['keyword_matched_count']}")
    lines.append(f"- Boundary matched packets: {summary.get('boundary_matched_count', 0)}")
    lines.append(f"- Fallback packets: {summary['fallback_count']}")
    lines.append(f"- Missing source files: {summary['source_missing_count']}")
    lines.append("")
    lines.append("The `Source Lines` column is an audit pointer to the local source-file line range used for each evidence snippet. It is not a business metric.")
    lines.append("")
    lines.append("| Factor | Source | Role | Status | Source Lines | Matched Terms | Local Evidence Snippet |")
    lines.append("|---|---|---|---|---|---|---|")

    for row in rows:
        lines.append(
            "| "
            + markdown_escape(row["factor_id"])
            + " | "
            + markdown_escape(row["source_path"])
            + " | "
            + markdown_escape(row["grounding_role"])
            + " | "
            + markdown_escape(row["grounding_status"])
            + " | "
            + markdown_escape(row["line_range"])
            + " | "
            + markdown_escape(", ".join(row["matched_terms"]))
            + " | "
            + markdown_escape(row["snippet"])
            + " |"
        )

    lines.append("")
    lines.append("## 5. Competing Hypotheses")
    lines.append("")
    lines.append(
        "Hypothesis confidence values are deterministic scenario-template values "
        "assigned by `generate_hypotheses(question_type)` in `rac/src/mock_pipeline.py`. "
        "They are not learned probabilities, calibrated likelihoods, or direct calculations "
        "from observed Meituan metric tables."
    )
    lines.append("")
    lines.append("| Hypothesis | Confidence | Status | Weakness |")
    lines.append("|---|---:|---|---|")

    for hypothesis in state["hypotheses"]:
        lines.append(
            "| "
            + markdown_escape(hypothesis["claim"])
            + " | "
            + f"{hypothesis['confidence']:.2f}"
            + " | "
            + markdown_escape(hypothesis["status"])
            + " | "
            + markdown_escape("; ".join(hypothesis["weaknesses"]))
            + " |"
        )

    lines.append("")
    lines.append("## 6. Critic Findings")
    lines.append("")

    for finding in state["critic_findings"]:
        lines.append(
            f"- [{finding['severity']}] {finding['issue']} "
            f"Recommendation: {finding['recommendation']}"
        )

    lines.append("")
    lines.append("## 7. Fact Check")
    lines.append("")
    lines.append(f"- Status: {state['fact_check']['status']}")

    if state["fact_check"]["unsupported_claims"]:
        lines.append("- Unsupported claims:")
        for claim in state["fact_check"]["unsupported_claims"]:
            lines.append(f"  - {claim}")
    else:
        lines.append("- Unsupported claims: none")

    if state["fact_check"]["definition_conflicts"]:
        lines.append("- Definition conflicts:")
        for conflict in state["fact_check"]["definition_conflicts"]:
            lines.append(f"  - {conflict}")
    else:
        lines.append("- Definition conflicts: none")

    lines.append("")
    lines.append("## 8. Final Judgment")
    lines.append("")
    lines.append(state["belief_update"]["claim"])
    lines.append("")
    lines.append(
        "The judgment remains conservative because local snippet matching grounds the evidence, "
        "but it does not prove causality or replace a full retrieval system."
    )
    lines.append("")

    coverage_score = calculate_evidence_coverage_score(state)

    lines.append("## 9. Evidence-Coverage Score")
    lines.append("")
    lines.append(f"{coverage_score['score']:.2f}")
    lines.append("")
    lines.append("How this score is calculated:")
    lines.append("")
    lines.append("```text")
    lines.append("evidence_coverage_score =")
    lines.append("  0.45 * direct_evidence_rate")
    lines.append("+ 0.25 * supported_or_boundary_rate")
    lines.append("+ 0.15 * no_missing_source_file_score")
    lines.append("+ 0.15 * no_fallback_score")
    lines.append("```")
    lines.append("")
    lines.append("Weight rationale:")
    lines.append("")
    lines.append("| Component | Weight | Why |")
    lines.append("|---|---:|---|")
    lines.append("| `direct_evidence_rate` | 0.45 | Highest priority because actual local evidence should matter more than boundary-only evidence. |")
    lines.append("| `supported_or_boundary_rate` | 0.25 | Boundary evidence is valuable because it explicitly records missing requirements instead of hiding them. |")
    lines.append("| `no_missing_source_file_score` | 0.15 | Source files must exist, but this is a basic traceability check rather than evidence strength. |")
    lines.append("| `no_fallback_score` | 0.15 | Fallback evidence is acceptable as a warning, but should reduce confidence in coverage. |")
    lines.append("")
    lines.append("Formula limitation:")
    lines.append("")
    lines.append("- These weights are fixed prototype heuristics.")
    lines.append("- They are not learned parameters, optimized thresholds, calibrated probabilities, or business-performance predictors.")
    lines.append("- The score is intended to make evidence-routing coverage inspectable, not to prove that a business conclusion is correct.")
    lines.append("")
    lines.append("Future sensitivity check:")
    lines.append("")
    lines.append("- A future version should run a small sensitivity check over alternative weight settings, similar to the Demo 2 guardrail sensitivity check.")
    lines.append("- If the final report interpretation changes sharply under small weight changes, the score should be treated as weight-sensitive evidence rather than a stable review signal.")
    lines.append("")
    lines.append("Current report inputs:")
    lines.append("")
    lines.append(f"- total_packets = {coverage_score['total_packets']}")
    lines.append(f"- keyword_matched_packets = {coverage_score['keyword_matched_packets']}")
    lines.append(f"- boundary_matched_packets = {coverage_score['boundary_matched_packets']}")
    lines.append(f"- fallback_packets = {coverage_score['fallback_packets']}")
    lines.append(f"- missing_source_files = {coverage_score['missing_source_files']}")
    lines.append(f"- direct_evidence_rate = keyword_matched_packets / total_packets = {coverage_score['direct_evidence_rate']:.2f}")
    lines.append(f"- supported_or_boundary_rate = (keyword_matched_packets + boundary_matched_packets) / total_packets = {coverage_score['supported_or_boundary_rate']:.2f}")
    lines.append(f"- no_missing_source_file_score = {coverage_score['no_missing_source_file_score']:.2f}")
    lines.append(f"- no_fallback_score = {coverage_score['no_fallback_score']:.2f}")
    lines.append("")
    lines.append("Interpretation boundary:")
    lines.append("")
    lines.append("- This is a deterministic evidence-routing coverage score for the current local report.")
    lines.append("- It is not a learned probability, Bayesian posterior, causal confidence score, or business-success probability.")
    lines.append("- Boundary-matched evidence can increase coverage because it explicitly records missing requirements instead of hiding them.")
    lines.append("- A high score means the report is well-covered by local evidence and explicit boundaries; it does not mean the business conclusion is certain.")
    lines.append("")

    lines.append("## 10. What Cannot Be Concluded")
    lines.append("")

    for limitation in state["belief_update"]["limitations"]:
        lines.append(f"- {limitation}")

    lines.append("")
    lines.append("## 11. Review-State Update")
    lines.append("")
    lines.append(f"- review_state_id: {state['belief_update']['belief_id']}")
    lines.append(f"- status: {state['belief_update']['status']}")
    lines.append("- validity_conditions:")

    for condition in state["belief_update"]["validity_conditions"]:
        lines.append(f"  - {condition}")

    lines.append("")
    return "\n".join(lines)


def run_grounded_pipeline(question: str, *, root: Path) -> dict[str, Any]:
    state = run_mock_pipeline(question)
    grounded = resolve_state_evidence(state, root=root)

    state["grounded_evidence"] = grounded
    state["grounded_evidence_rows"] = build_grounded_evidence_rows(grounded)
    state["final_report"] = write_grounded_final_report(state)

    return state


def save_grounded_outputs(
    state: dict[str, Any],
    output_dir: Path,
    name: str | None = None
) -> dict[str, str]:
    output_dir.mkdir(parents=True, exist_ok=True)

    slug = name or slugify(state["question"])
    json_path = output_dir / f"grounded_{slug}.json"
    md_path = output_dir / f"grounded_{slug}.md"

    json_path.write_text(
        json.dumps(state, ensure_ascii=False, indent=2),
        encoding="utf-8"
    )

    md_path.write_text(
        state["final_report"],
        encoding="utf-8"
    )

    return {
        "json": str(json_path),
        "markdown": str(md_path)
    }
